config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users
  resources :courses
  root 'dashboards#index'
  resources :dashboards
  resources :klasses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :klass
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
end

app/models/klass.rb
class Klass < ApplicationRecord
  has_many :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:name, :lastname, :email,
      :password, :password_confirmation, :usertype)}

    devise_parameter_sanitizer.permit(:accout_update) {|u| u.permit(:name, :email,
      :password, :password_confirmation, :usertype)}
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new

  end

  # GET /courses/1/edit
  def edit
    @klasses = Klass.all
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :coursecode, :responsibleperson, :startdate, :enddate, :klass_id)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.fetch(:dashboard, {})
    end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_klass, only: [:show, :edit, :update, :destroy]

  # GET /klasses
  # GET /klasses.json
  def index
    @klasses = Klass.all
  end

  # GET /klasses/1
  # GET /klasses/1.json
  def show
  end

  # GET /klasses/new
  def new
    @klass = Klass.new
  end

  # GET /klasses/1/edit
  def edit
  end

  # POST /klasses
  # POST /klasses.json
  def create
    @klass = Klass.new(klass_params)

    respond_to do |format|
      if @klass.save
        format.html { redirect_to @klass, notice: 'Class was successfully created.' }
        format.json { render :show, status: :created, location: @klass }
      else
        format.html { render :new }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /klasses/1
  # PATCH/PUT /klasses/1.json
  def update
    respond_to do |format|
      if @klass.update(klass_params)
        format.html { redirect_to @klass, notice: 'Class was successfully updated.' }
        format.json { render :show, status: :ok, location: @klass }
      else
        format.html { render :edit }
        format.json { render json: @klass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /klasses/1
  # DELETE /klasses/1.json
  def destroy
    @klass.destroy
    respond_to do |format|
      format.html { redirect_to klasses_url, notice: 'Class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_klass
      @klass = Klass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def klass_params
      params.require(:klass).permit(:klass)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :coursecode %>
    <%= f.text_field :coursecode %>
  </div>

  <div class="field">
    <%= f.label :responsibleperson %>
    <%= f.text_field :responsibleperson %>
  </div>

  <div class="field">
    <%= f.label :startdate %>
    <%= f.date_select :startdate %>
  </div>

  <div class="field">
    <%= f.label :enddate %>
    <%= f.date_select :enddate %>
  </div>

  <div class="field">
    <%= f.label :enddate %>
    <%= collection_select(:course, :klass_id, Klass.all, :id, :klass, {}, {multiple: false})%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Coursecode</th>
      <th>Responsibleperson</th>
      <th>Class</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.coursecode %></td>
        <td><%= course.responsibleperson %></td>
        <% if course.klass_id? %>
          <td><%= course.klass.klass %></td>
        <% else %>
          <td><%= "no class" %></td>
        <% end %>
        <td><%= course.startdate %></td>
        <td><%= course.enddate %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>
<%= link_to 'Go to Dashboard', dashboards_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Coursecode:</strong>
  <%= @course.coursecode %>
</p>

<p>
  <strong>Responsibleperson:</strong>
  <%= @course.responsibleperson %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @course.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @course.enddate %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/dashboards/_form.html.erb
<%= form_for(dashboard) do |f| %>
  <% if dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dashboards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= link_to 'Show', dashboard %></td>
        <td><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
        <td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Classes', klasses_path %>
<%= link_to 'Courses', courses_path %>
<%= link_to 'Student', users_index_path %>
<%= link_to 'Log Out',  destroy_user_session_path, method: :delete %>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form', dashboard: @dashboard %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/klasses/_form.html.erb
<%= form_for(klass) do |f| %>
  <% if klass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(klass.errors.count, "error") %> prohibited this klass from being saved:</h2>

      <ul>
      <% klass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :klass %>
    <%= f.text_field :klass %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/klasses/edit.html.erb
<h1>Editing Class</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Show', @klass %> |
<%= link_to 'Back', klasses_path %>

app/views/klasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classes</h1>

<table>
  <thead>
    <tr>
      <th>Class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @klasses.each do |klass| %>
      <tr>
        <td><%= klass.klass %></td>
        <td><%= link_to 'Show', klass %></td>
        <td><%= link_to 'Edit', edit_klass_path(klass) %></td>
        <td><%= link_to 'Destroy', klass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class', new_klass_path %>
<%= link_to 'Go to Dashboard', dashboards_path %>

app/views/klasses/new.html.erb
<h1>New Class</h1>

<%= render 'form', klass: @klass %>

<%= link_to 'Back', klasses_path %>

app/views/klasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Klass:</strong>
  <%= @klass.klass %>
</p>

<%= link_to 'Edit', edit_klass_path(@klass) %> |
<%= link_to 'Back', klasses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyTeacher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user_registration_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Go to Dashboard', dashboards_path %>